[build]
  command = "npm run build && ls -R src"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"  # Match your local Node.js version
  VITE_LOG_LEVEL = "info"  # This will give you more detailed logs to help with debugging